### ISSUE TITLE
original paper related to the fin ray code

### ISSUE THREAD

**Issue by joanwu95** [zeyang23/Fin-ray#1]
Hello, hope not disturbing you. I'm very interested in your intrinsic force sensing code of fin ray gripper. But I couldn't find the corresponding paper in ZhiWang, WanFang, or in Google. Would you mind provide a link or a title with which I could find the paper? Many thanks!!!!!!

**Comment by zeyang23** [comment]
Hello @joanwu95 ~
Sorry for the late reply.
This fin-ray project is my undergraduate thesis, which is not available on the Internet.
The basic idea is to establish the force-deflection model of fin-ray. The deflection can be detected by the sensors on the back of fin-ray. The contact force is then estimated using the deflection and the model.
